---
- name: Setup PostgreSQL
  hosts: databases
  become: true
  tags:
    - setup
  tasks:
    - name: Install PostgreSQL 15
      dnf:
        name: postgresql15-server
        state: latest

    - name: Start PostgreSQL 15
      systemd:
        name: postgresql-15
        state: started
        enabled: yes

- name: Download and install demo small DB
  hosts: databases
  become: true
  gather_facts: false
  tags:
    - demo_db
  tasks:
    - name: Download archive
      get_url:
        url: https://edu.postgrespro.ru/demo_small.zip
        dest: /tmp/demo_small.zip

    - name: Unarchive files
      unarchive:
        src: /tmp/demo_small.zip
        dest: /tmp/demo_small
        remote_src: yes

    - name: Run setup script
      shell: psql -U postgres -d postgres -a -f /tmp/demo_small/setup.sql
      args:
        chdir: /tmp/demo_small

    - name: Delete temporary download and extracted files
      file:
        path: "/tmp/{{ item }}"
        state: absent
      loop:
        - demo_small.zip
        - demo_small